"""
Gateway API request/response schemas.

Defines the contract used by the unified gateway:
- QueryRequest: incoming query from clients
- QueryResponse: normalized answer returned to clients
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class QueryRequest(BaseModel):
    """
    Request model for unified gateway queries.

    Fields:
        query: Natural language question from the user.
        workflow: Routing workflow selector
                  (auto|general|amazon_docs|ic_docs|sp_api|uds).
        rewrite_enable: Whether to enable query rewriting.
        session_id: Optional session identifier for multi-turn context.
        stream: Whether client requests streaming response (SSE).
    """

    query: str = Field(..., description="Natural language user query")
    workflow: str = Field(
        default="auto",
        description=(
            "Workflow selector: auto|general|amazon_docs|ic_docs|sp_api|uds. "
            "Defaults to auto when not provided."
        ),
    )
    rewrite_enable: bool = Field(
        default=True,
        description="Enable or disable query rewriting.",
    )
    rewrite_backend: Optional[str] = Field(
        default=None,
        description=(
            "Rewrite backend when rewrite_enable=True: 'ollama' or 'deepseek'. "
            "Ignored when rewrite_enable=False. Defaults to GATEWAY_REWRITE_BACKEND env."
        ),
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session identifier for multi-turn context.",
    )
    user_id: Optional[str] = Field(
        default=None,
        description="User identifier when logged in; used for user-scoped conversation history.",
    )
    stream: bool = Field(
        default=False,
        description="If true, client prefers streaming responses (SSE).",
    )

    @field_validator("rewrite_backend", mode="before")
    @classmethod
    def _normalize_rewrite_backend(cls, v: Optional[str]) -> Optional[str]:
        if v is None or (isinstance(v, str) and not v.strip()):
            return None
        s = str(v).strip().lower()
        return s if s in ("ollama", "deepseek") else None

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "query": "What were my total Amazon sales last week?",
                "workflow": "uds",
                "rewrite_enable": True,
                "rewrite_backend": "ollama",
                "session_id": "session-1234",
                "user_id": None,
                "stream": False,
            }
        },
    )


class QueryResponse(BaseModel):
    """
    Response model for unified gateway answers.

    Fields:
        answer: Final answer text for the user.
        workflow: Workflow that handled the query.
        routing_confidence: Confidence score for routing decision (0.0–1.0).
        sources: List of source metadata dicts (documents, tables, etc.).
        request_id: Unique identifier for this gateway request.
        error: Optional error message when the request fails.
        debug: Optional rewrite/routing trace metadata for observability.
    """

    answer: str = Field(
        default="",
        description="Final answer text for the user.",
    )
    workflow: str = Field(
        default="auto",
        description="Workflow that produced this answer.",
    )
    routing_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence score for routing decision (0.0–1.0).",
    )
    sources: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of source metadata dicts (documents, tables, etc.).",
    )
    request_id: str = Field(
        ...,
        description="Unique identifier for this gateway request.",
    )
    error: Optional[str] = Field(
        default=None,
        description="Optional error message when the request fails.",
    )
    debug: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "Optional debug trace. Includes rewritten query, rewrite latency, "
            "and route-input metadata."
        ),
    )
    plan: Optional["RewritePlan"] = Field(
        default=None,
        description="Optional structured execution plan generated by planner rewrite.",
    )
    task_results: List["TaskExecutionResult"] = Field(
        default_factory=list,
        description="Per-task execution outcomes for multi-task planned queries.",
    )
    merged_answer: Optional[str] = Field(
        default=None,
        description="Merged final answer assembled from successful task results.",
    )
    clarification_required: bool = Field(
        default=False,
        description="True when query is ambiguous; answer contains clarification question.",
    )
    clarification_question: Optional[str] = Field(
        default=None,
        description="Question to ask user for clarification.",
    )
    pending_query: Optional[str] = Field(
        default=None,
        description="Original query when clarification is needed; client merges with follow-up.",
    )
    clarification_backend: Optional[str] = Field(
        default=None,
        description="Backend used for clarification: ollama or deepseek.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "answer": "Your total Amazon sales last week were $12,345.",
                "workflow": "uds",
                "routing_confidence": 0.96,
                "sources": [
                    {
                        "type": "table",
                        "name": "amz_order",
                        "rows_scanned": 1024,
                    }
                ],
                "request_id": "req-1234",
                "error": None,
                "debug": {
                    "original_query": "What were my total Amazon sales last week?",
                    "rewritten_query": "total Amazon sales last week",
                    "rewrite_enabled": True,
                    "rewrite_backend": "ollama",
                    "rewrite_time_ms": 24,
                    "route_input_query": "total Amazon sales last week",
                    "route_source": "heuristic",
                    "route_backend": None,
                    "route_llm_confidence": None,
                },
            }
        },
    )


class RewriteResponse(BaseModel):
    """
    Response model for rewrite-only endpoint.

    Fields:
        original_query: Original user query text.
        rewritten_query: Query text after normalization/rewriting.
        rewrite_enabled: Whether rewriting was enabled for this request.
        rewrite_backend: Effective rewrite backend used, if any.
        rewrite_time_ms: Rewrite elapsed time in milliseconds.
    """

    original_query: str = Field(..., description="Original user query text.")
    rewritten_query: str = Field(..., description="Rewritten query text.")
    rewrite_enabled: bool = Field(
        default=True,
        description="Whether rewriting was enabled for this request.",
    )
    rewrite_backend: Optional[str] = Field(
        default=None,
        description="Effective rewrite backend used for this request.",
    )
    rewrite_time_ms: int = Field(
        default=0,
        ge=0,
        description="Rewrite elapsed time in milliseconds.",
    )
    plan: Optional["RewritePlan"] = Field(
        default=None,
        description="Always None from rewrite endpoint. Plan is built by Dispatcher in /query flow.",
    )
    clarification_required: bool = Field(
        default=False,
        description="True when query is ambiguous; user should provide more context.",
    )
    clarification_question: Optional[str] = Field(
        default=None,
        description="Question to ask user when clarification_required is True.",
    )
    pending_query: Optional[str] = Field(
        default=None,
        description="Original query when clarification is needed.",
    )
    clarification_status: Optional[str] = Field(
        default=None,
        description="Clarification check status: Complete (ran, no ambiguity), Skip (disabled), Required (returned early).",
    )
    clarification_backend: Optional[str] = Field(
        default=None,
        description="Backend used for clarification: ollama or deepseek.",
    )
    memory_rounds: int = Field(
        default=0,
        ge=0,
        description="Number of short-term memory rounds integrated (0 when no session/history).",
    )
    memory_text_length: int = Field(
        default=0,
        ge=0,
        description="Character count of short-term memory context integrated (0 when none).",
    )
    rewritten_query_length: int = Field(
        default=0,
        ge=0,
        description="Character count of the rewritten query.",
    )
    intents: Optional[List[str]] = Field(
        default=None,
        description="Intent classification list: split sub-questions from rewritten query (for UI bullet list).",
    )
    intent_details: Optional[List[Dict[str, str]]] = Field(
        default=None,
        description=(
            "Per sub-intent classification details. "
            "Each item: {intent, workflow, keyword, vector}. "
            "workflow is the final per-intent classification result."
        ),
    )
    workflows: Optional[List[str]] = Field(
        default=None,
        description="Intent classification result: workflow names (e.g. general, amazon_docs, uds, sp_api).",
    )
    rewritten_query_display: Optional[str] = Field(
        default=None,
        description="Bullet-point formatted rewritten query for UI display. Use when present.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "original_query": "Total sales in October 2025",
                "rewritten_query": "total sales for October 2025",
                "rewrite_enabled": True,
                "rewrite_backend": "ollama",
                "rewrite_time_ms": 18,
            }
        }
    )


class TaskItem(BaseModel):
    """
    Executable task item produced by planner rewrite.

    Fields:
        task_id: Unique task id inside the current request.
        workflow: Target workflow for this task.
        query: Agent-ready task query.
        depends_on: Optional upstream task ids that this task depends on.
        reason: Optional explanation for planner decision.
    """

    task_id: str = Field(..., description="Task identifier.")
    workflow: str = Field(
        ...,
        description="Target workflow: general|amazon_docs|ic_docs|sp_api|uds.",
    )
    query: str = Field(..., description="Agent-ready query for this task.")
    depends_on: List[str] = Field(
        default_factory=list,
        description="Optional upstream task ids required before execution.",
    )
    reason: Optional[str] = Field(
        default=None,
        description="Optional planner rationale for this task.",
    )


class TaskGroup(BaseModel):
    """
    Group of tasks that can be executed together.
    """

    group_id: str = Field(..., description="Task group identifier.")
    parallel: bool = Field(
        default=True,
        description="Whether tasks inside this group can execute in parallel.",
    )
    tasks: List[TaskItem] = Field(
        default_factory=list,
        description="Tasks in this execution group.",
    )


class RewritePlan(BaseModel):
    """
    Structured planner output for gateway multi-task execution.
    """

    plan_type: str = Field(
        default="single_domain",
        description="Plan type: single_domain or hybrid.",
    )
    task_groups: List[TaskGroup] = Field(
        default_factory=list,
        description="Ordered execution groups of tasks.",
    )
    merge_strategy: str = Field(
        default="concat",
        description="How task outputs should be merged (none|concat|compare|synthesize).",
    )
    extracted_intents: Optional[List[str]] = Field(
        default=None,
        description=(
            "Optional list of distinct sub-questions extracted from user query. "
            "Used when LLM merges tasks: fallback builds one task per intent."
        ),
    )


class TaskExecutionResult(BaseModel):
    """
    Per-task execution result captured by the gateway orchestrator.
    """

    task_id: str = Field(..., description="Task identifier.")
    workflow: str = Field(..., description="Workflow executed for this task.")
    query: str = Field(..., description="Task query sent to downstream backend.")
    status: str = Field(
        default="completed",
        description="Execution status: completed|failed|skipped.",
    )
    answer: str = Field(default="", description="Task answer text.")
    sources: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Task-level source metadata.",
    )
    error: Optional[str] = Field(
        default=None,
        description="Task-level error message when execution fails.",
    )
    duration_ms: int = Field(
        default=0,
        ge=0,
        description="Task execution duration in milliseconds.",
    )


QueryResponse.model_rebuild()
RewriteResponse.model_rebuild()
